{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Introdução ao Método Científico\n",
    "\n",
    "Prof. Daniel de Abreu Pereira Uhr\n",
    "\n",
    "\n",
    "\n",
    "## Conteúdo\n",
    "\n",
    "* Conhecimento, Epistemologia e o Método Científico\n",
    "  * Áreas do Conhecimento\n",
    "  * Epistemologia\n",
    "  * Epistemologias Contemporâneas\n",
    "  * Epistemologia de Karl Popper\n",
    "  * Ciência Econômica e o Método Científico\n",
    "\n",
    "\n",
    "\n",
    "## Referências\n",
    "\n",
    "**Principais**\n",
    "\n",
    "* Karl Popper. A Lógica da Pesquisa Científica. Editora Cultrix. 2013. São Paulo.\n",
    "* Gewandsznajder, F. O que é o método científico? Editora Brasiliense. 1985. São Paulo.\n",
    "* Karl Popper. Conhecimento Objetivo. Editora Itatiaia. 1975. Belo Horizonte.\n",
    "* Notas próprias do professor.\n",
    "\n",
    "**Observações:** O material apresentado aqui é uma adaptação do material de aula do Prof. Daniel de Abreu Pereira Uhr, e não deve ser utilizado para fins comerciais. O material é disponibilizado para fins educacionais e de pesquisa, e não deve ser reproduzido sem a devida autorização do autor. Este material pode conter erros e imprecisões. O autor não se responsabiliza por quaisquer danos ou prejuízos decorrentes do uso deste material. O uso deste material é de responsabilidade exclusiva do usuário. Caso você encontre erros ou imprecisões neste material, por favor, entre em contato com o autor para que possam ser corrigidos. O autor agradece qualquer *feedback* ou sugestão de melhoria.\n",
    "\n",
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Conhecimento, Epistemologia e o Método Científico\n",
    "\n",
    "### Áreas do Conhecimento\n",
    "\n",
    "Áreas do conhecimento humano (Ramos da Filosofia)\n",
    "\n",
    "1. **Estética**: Envolve a reflexão sobre a beleza e o valor estético, explorando questões relacionadas à arte, ao gosto e à experiência estética.\n",
    "2. **Ética**:\n",
    "    * **Moral**: Reflete sobre a conduta humana, muitas vezes influenciada pela cultura, tradição e religião.\n",
    "    * **Ética**: Reflete sobre o comportamento moral em um sentido mais amplo, considerando princípios éticos universais e dilemas morais.\n",
    "3. **Lógica**: Estuda as regras do raciocínio válido, ajudando a distinguir argumentos válidos de argumentos inválidos.\n",
    "4. **Metafísica**:\n",
    "    * **Ontologia**: Explora questões fundamentais sobre a realidade e a existência (o que existe e como existe - o que há/ser), incluindo a natureza da mente e da matéria, bem como as categorias fundamentais do ser.\n",
    "    * **Cosmologia**: Investigação sobre a natureza do universo como um todo e a busca pela unificação do conhecimento sobre o cosmos.\n",
    "5. **Epistemologia**: Teoria do conhecimento que examina a natureza, origens e limites do conhecimento humano, incluindo questões sobre crença, justificação, verdade e certeza.\n",
    "\n",
    "\n",
    "### Epistemologia\n",
    "\n",
    "**Histórico**\n",
    "\n",
    "**Platão e Aristóteles**: Ambos foram importantes na história da epistemologia. Platão, por exemplo, enfatizou a importância das ideias e do conhecimento a priori, enquanto Aristóteles concentrou-se mais na observação e na experiência empírica como fontes de conhecimento.\n",
    "\n",
    "**Filósofos Racionalistas**: Descartes, Spinoza e Leibniz são considerados racionalistas, pois enfatizaram a razão como a principal fonte de conhecimento. Eles argumentavam que certas verdades poderiam ser conhecidas apenas pela razão e pela dedução lógica, independentemente da experiência sensorial.\n",
    "\n",
    "**Filósofos do Empirismo Inglês**: Bacon, Locke e Hume representam o empirismo, que valoriza a experiência sensorial como a base do conhecimento. Eles argumentavam que todo conhecimento humano vem da experiência, seja por meio da observação direta ou da indução.\n",
    "\n",
    "**Immanuel Kant**: Kant foi um importante filósofo que tentou reconciliar o racionalismo e o empirismo. Ele argumentou que parte do conhecimento é a priori, derivada da estrutura inata da mente humana, enquanto outra parte vem da experiência sensorial.\n",
    "\n",
    "**Epistemologias Contemporâneas**: Thomas Kuhn, Imre Lakatos e Karl Popper contribuíram significativamente para a epistemologia moderna com suas teorias sobre a natureza da ciência, a mudança de paradigmas científicos e a metodologia da investigação científica.\n",
    "\n",
    "\n",
    "### Epistemologias Contemporâneas\n",
    "\n",
    "**Thomas Kuhn (1922-1996):**\n",
    "\n",
    "<div style=\"text-align:center;\">\n",
    "    <img src=\"images\\Thomas.png\"  alt=\"Imagem\" style=\"width: 200px;\"/>\n",
    "</div>\n",
    "\n",
    "* Kuhn introduziu o conceito de **\"ciência normal\"** e **\"paradigma\"** para descrever a prática científica. Ele argumentou que a ciência não progride de maneira linear e gradual, mas sim por meio de revoluções científicas, nas quais os paradigmas estabelecidos são substituídos por novos.\n",
    "Sua ideia de **paradigma destaca a importância das crenças compartilhadas e das práticas dentro de uma comunidade científica na formação do conhecimento**.\n",
    "\n",
    "\n",
    "**Imre Lakatos (1922-1974):**\n",
    "<div style=\"text-align:center;\">\n",
    "    <img src=\"images\\Imre.png\"  alt=\"Imagem\" style=\"width: 200px;\"/>\n",
    "</div>\n",
    "\n",
    "* Lakatos desenvolveu a ideia de **\"programas de pesquisa científica\"**, que são conjuntos de teorias e métodos que guiam a investigação em uma determinada área do conhecimento.\n",
    "Ele enfatizou a importância da continuidade e do desenvolvimento progressivo dentro desses programas, mesmo diante de desafios e mudanças.\n",
    "\n",
    "\n",
    "**Karl Popper (1902-1994):**\n",
    "\n",
    "<div style=\"text-align:center;\">\n",
    "    <img src=\"images\\Karl.png\"  alt=\"Imagem\" style=\"width: 200px;\"/>\n",
    "</div>\n",
    "\n",
    "\n",
    "* Popper propôs o **\"racionalismo crítico\"** como uma **abordagem para a investigação científica**. Ele argumentou que **o objetivo da ciência não é confirmar teorias**, mas sim **refutá-las** por meio de testes rigorosos. O critério de demarcação de Popper para distinguir a ciência da não-ciência é a falsificabilidade - a capacidade de uma teoria ser empiricamente testada e, potencialmente, refutada. \n",
    "\n",
    "\n",
    "### Epistemologia de Karl Popper\n",
    "\n",
    "**Método Hipotético-Dedutivo:**\n",
    "* Popper defendia a ideia de que a ciência avança por meio da formulação de hipóteses, que são então testadas de forma rigorosa e sistemática para tentar refutá-las. Esse processo é conhecido como **método hipotético-dedutivo**.\n",
    " \n",
    "**Critério de Falsificação:**\n",
    "* Popper propôs que a capacidade de uma teoria ser empiricamente testada e, potencialmente, refutada é o critério de demarcação entre ciência e pseudociência. Isso significa que uma teoria científica deve ser formulada de maneira que possa ser falsificada por meio de evidências empíricas.\n",
    "\n",
    "**Pseudociências:**\n",
    "* Popper identificou várias áreas do conhecimento, como astrologia, psicanálise e parapsicologia, como pseudociências, porque suas hipóteses não podem ser submetidas a testes rigorosos de falsificação.\n",
    "\n",
    "**Universalidade do Critério de Demarcação:**\n",
    "* A ideia de falsificação como critério de demarcação entre ciência e não-ciência é considerada por Popper como aplicável a todas as áreas do conhecimento, incluindo Biologia, Química, Física, Medicina, (Economia?), etc...\n",
    "\n",
    "**Natureza da Ciência:**\n",
    "* Popper enfatizou que na ciência não existe uma verdade absoluta ou final. Em vez disso, ***as teorias científicas são sempre provisórias e sujeitas a revisão com base em novas evidências e experimentos***.\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "### Ciência Econômica e o Método Científico\n",
    "\n",
    "**Ciência Econômica:** é o campo do conhecimento que estuda a as **decisões dos agentes econômicos**. Tanto **em nível microeconômico**, quanto **em nível macroeconômico**.\n",
    "\n",
    "* **Natureza Humana** (racionalidade econômica)\n",
    "  * **Comportamento maximizador** dos agentes econômicos; Análise de custo e benefício; Análise de decisão dinâmica; (Decisão individual)\n",
    "  * **Princípio de Equilíbrio**; (interação entre agentes econômicos)\n",
    "\n",
    "Relacionar o campo de pesquisa da economia com o método científico de Popper envolve aplicar os princípios popperianos de falsificação e testabilidade às teorias econômicas. \n",
    "  \n",
    "* **Formulação de Hipóteses:** Na ciência econômica, as teorias são frequentemente formuladas com base em hipóteses sobre o comportamento dos agentes econômicos, como consumidores, empresas e governos. Por exemplo, uma hipótese pode ser que os consumidores tomam decisões visando maximizar sua utilidade.\n",
    "\n",
    "* **Testabilidade:** As teorias econômicas devem ser formuladas de maneira que possam ser testadas empiricamente. Isso pode envolver a coleta de dados e a realização de experimentos ou análises estatísticas para verificar se as previsões da teoria se confirmam na prática.\n",
    "\n",
    "* **Falsificação:** De acordo com o critério de demarcação popperiano, uma teoria científica deve ser formulada de maneira que possa ser potencialmente refutada por meio de evidências empíricas. Portanto, na ciência econômica, as teorias devem ser sujeitas a testes que possam potencialmente falsificá-las.\n",
    "\n",
    "* **Progresso Científico:** No contexto das ciências econômicas, o progresso científico ocorre quando as teorias existentes são submetidas a testes rigorosos e algumas delas são refutadas, levando ao desenvolvimento de novas teorias mais robustas e capazes de explicar os fenômenos econômicos de forma mais precisa.\n",
    "\n",
    "Portanto, ao aplicar o **método científico popperiano às ciências econômicas**, os economistas são incentivados a formular teorias que sejam testáveis, sujeitas à falsificação e que possam contribuir para o avanço do conhecimento econômico por meio da análise empírica e da revisão crítica das teorias existentes."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
